INSERT INTO NAVIGACNIBOD ( NAVOBJEK_ID ) VALUES ( 
'MEL  '); 
INSERT INTO NAVIGACNIBOD ( NAVOBJEK_ID ) VALUES ( 
'BER  '); 
INSERT INTO NAVIGACNIBOD ( NAVOBJEK_ID ) VALUES ( 
'LIB  '); 
commit;
 
