INSERT INTO NAVOBJEKT ( ID, NAZEV, ZEMSIRKA, ZEMDELKA, VYSKAMSL ) VALUES ( 
'RUZYN', 'Ruzyne intl. airport', 14.125, 52.75, 372); 
INSERT INTO NAVOBJEKT ( ID, NAZEV, ZEMSIRKA, ZEMDELKA, VYSKAMSL ) VALUES ( 
'KBELY', 'Letiste Kbely', 14.23, 52.5, 420); 
INSERT INTO NAVOBJEKT ( ID, NAZEV, ZEMSIRKA, ZEMDELKA, VYSKAMSL ) VALUES ( 
'BRNO ', 'Brno intl. airport', 17.822, 50.014, 264); 
INSERT INTO NAVOBJEKT ( ID, NAZEV, ZEMSIRKA, ZEMDELKA, VYSKAMSL ) VALUES ( 
'MEL  ', 'Melnik VORDME', 14.17, 53, 300); 
INSERT INTO NAVOBJEKT ( ID, NAZEV, ZEMSIRKA, ZEMDELKA, VYSKAMSL ) VALUES ( 
'BER  ', 'Beroun VOR', 13.85, 52.05, 479); 
INSERT INTO NAVOBJEKT ( ID, NAZEV, ZEMSIRKA, ZEMDELKA, VYSKAMSL ) VALUES ( 
'LIB  ', 'Liberec VORDME', 14.51, 56.4, 745); 
commit;
 
