INSERT INTO TYPLETADLA ( CISLOSCHVALENI, VYROBCE, NAZEV, TRIDA,
PASAZERU ) VALUES ( 
445784, 'Boeing', 'Boeing 757-300', 'B', 150); 
INSERT INTO TYPLETADLA ( CISLOSCHVALENI, VYROBCE, NAZEV, TRIDA,
PASAZERU ) VALUES ( 
449554, 'Cessna', 'Cessna Skyplane IV', 'N', 4); 
INSERT INTO TYPLETADLA ( CISLOSCHVALENI, VYROBCE, NAZEV, TRIDA,
PASAZERU ) VALUES ( 
150454, 'McDonnell Douglas', 'F-2 Phantom', 'M', 2); 
INSERT INTO TYPLETADLA ( CISLOSCHVALENI, VYROBCE, NAZEV, TRIDA,
PASAZERU ) VALUES ( 
460487, 'Let Kunovice', 'L-47 Zlin', 'A', 1); 
commit;
 
