INSERT INTO PLANPRESBOD ( PORADIVPLANU, LETOVYPL_SCHVALCISLO,
NAVIGACN_NAVOBJEK_ID ) VALUES ( 
0, 100253, 'MEL  '); 
INSERT INTO PLANPRESBOD ( PORADIVPLANU, LETOVYPL_SCHVALCISLO,
NAVIGACN_NAVOBJEK_ID ) VALUES ( 
1, 100253, 'LIB  '); 
INSERT INTO PLANPRESBOD ( PORADIVPLANU, LETOVYPL_SCHVALCISLO,
NAVIGACN_NAVOBJEK_ID ) VALUES ( 
0, 100255, 'BER  '); 
INSERT INTO PLANPRESBOD ( PORADIVPLANU, LETOVYPL_SCHVALCISLO,
NAVIGACN_NAVOBJEK_ID ) VALUES ( 
0, 100256, 'LIB  '); 
INSERT INTO PLANPRESBOD ( PORADIVPLANU, LETOVYPL_SCHVALCISLO,
NAVIGACN_NAVOBJEK_ID ) VALUES ( 
1, 100256, 'MEL  '); 
INSERT INTO PLANPRESBOD ( PORADIVPLANU, LETOVYPL_SCHVALCISLO,
NAVIGACN_NAVOBJEK_ID ) VALUES ( 
0, 100257, 'BER  '); 
commit;
 
