INSERT INTO REGLETADLO ( PROVOZOV_ID, TYP_CISLOSCHVALENI, ID ) VALUES ( 
1, 445784, 'OK-OSTRAVA'); 
INSERT INTO REGLETADLO ( PROVOZOV_ID, TYP_CISLOSCHVALENI, ID ) VALUES ( 
2, 445784, 'OK-BLZC   '); 
INSERT INTO REGLETADLO ( PROVOZOV_ID, TYP_CISLOSCHVALENI, ID ) VALUES ( 
3, 449554, 'OK-NOV    '); 
INSERT INTO REGLETADLO ( PROVOZOV_ID, TYP_CISLOSCHVALENI, ID ) VALUES ( 
1, 449554, 'OK-MALACSA'); 
INSERT INTO REGLETADLO ( PROVOZOV_ID, TYP_CISLOSCHVALENI, ID ) VALUES ( 
4, 150454, 'BRAVO4    '); 
INSERT INTO REGLETADLO ( PROVOZOV_ID, TYP_CISLOSCHVALENI, ID ) VALUES ( 
5, 460487, 'OK-AKRO1  '); 
commit;
 
